# Database configuration - Using SQLite for local development
DATABASE_URL = "sqlite:///leave_management.db"

# For production deployment with Supabase PostgreSQL:
# DATABASE_URL = "postgresql://postgres:Aa.01017234828!@db.wejbgeihnluhufvzdwee.supabase.co:5432/postgres"

# For production deployment, use environment variables:
# DATABASE_URL = "${DATABASE_URL}"

# Google OAuth (for future use)
# GOOGLE_CLIENT_ID = "your-client-id"
# GOOGLE_CLIENT_SECRET = "your-client-secret"

# Email configuration (for future use)
# EMAIL_HOST = "smtp.gmail.com"
# EMAIL_PORT = 587
# EMAIL_USER = "your-email@tempo.fit"
# EMAIL_PASSWORD = "your-password"

# Application settings
APP_NAME = "Leave Management System"
COMPANY_NAME = "Tempo.fit"
COMPANY_DOMAIN = "tempo.fit" 